deploy pipeline update
improved error catching, added build and nginx

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,10 +15,20 @@ jobs:
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SERVER_KEY }}
           script: |
-            echo "Successfully connected to Azure!"
-            
-            cd ${{ secrets.SERVER_PATH }}
-            
-            git pull origin main
-            
-            echo "Deployment successful on Azure!"
+            echo "Succesfully connected to Azure!"
+
+            # pulling code from GitHub into the main folder
+            echo "[PULL] Moving to root directory..."
+            cd ${{ secrets.SERVER_PATH }} && git pull origin main && echo "[OK] Pulling succesfully executed!" || { echo "[ERROR] Pulling failed!"; exit 1; }
+
+            # building the website for production use
+            cd ${{ secrets.WEBSITE_PATH }} && npm install && npm run build && echo "[OK] Building succesfully executed!" || { echo "[ERROR] Building failed..."; exit 1; }
+
+            # nginx
+            echo "[NGINX] Reloading..."
+            sudo service nginx reload && echo "Deployment successful on Azure!" || { echo "Deployment failed!"; exit 1; }
+
+
+
+
+
